export default {
  'en': {
    currency_unit: ' USD',
    loginPage_AppTitle: 'Expensify',
    loginPage_Message: 'It\'s time to get your expenses under control',
    loginPage_LoginBtn: 'Login with Google',
    header_title: 'Expensify',
    header_buttonLabel: 'logout',
    header_langBtn: 'عربي',
    summary_message_viewing: 'Viewing ',
    summary_message_total: ' expenses totalling ',
    summary_noMessages: 'There are no expenses to view',
    addExpense_btn: 'Add Expense',
    filter_search_lable: 'Search for',
    filter_search_input: 'expense description',
    filter_sort_label: 'Sort by',
    filter_sort_amount: 'amount',
    filter_sort_date: 'date',
    filter_dateRange_from: 'from date',
    filter_dateRange_to: 'to date',
    list_header_expenses: 'Expenses',
    list_header_expense: 'Expense',
    list_header_amount: 'Amount',
    list_noExpense: 'No expenses',
    add_heading: 'Add Expense',
    add_description: 'description',
    add_amount: 'amount (in USD)',
    add_note: 'add a note for your expense (optional)',
    add_btn_label_add: 'Add Expense',
    add_btn_label_save: 'Save Changes',
    add_error_msg: 'Please provide description and amount',
    edit_heading: 'Edit Expense',
    edit_btn_remove: 'Remove',
    edit_btn_cancel: 'Cancel'
  },
  'ar': {
    currency_unit: ' ل.س.',
    loginPage_AppTitle: 'فواتير',
    loginPage_Message: 'حان الوقت لمراجعة و سداد فواتيرك',
    loginPage_LoginBtn: 'تسجيل دخول عبر غوغل',
    header_title: 'فواتير',
    header_buttonLabel: 'تسجيل خروج',
    header_langBtn: 'English',
    summary_message_viewing: 'عرض ',
    summary_message_total: ' من الفواتير بقيمة ',
    summary_noMessages: 'لا يوجد فواتير للعرض',
    addExpense_btn: 'إضافة فاتورة',
    filter_search_lable: 'البحث عن',
    filter_search_input: 'وصف الفاتورة',
    filter_sort_label: 'ترتيب حسب',
    filter_sort_amount: 'القيمة',
    filter_sort_date: 'التاريخ',
    filter_dateRange_from: 'من تاريخ',
    filter_dateRange_to: 'حتى تاريخ',
    list_header_expenses: 'فواتير',
    list_header_expense: 'فاتورة',
    list_header_amount: 'القيمة',
    list_noExpense: 'لا يوجد فواتير',
    add_heading: 'إضافة فاتورة',
    add_description: 'أسم أو وصف',
    add_amount: 'القيمة (ل.س.)',
    add_note: 'ملاحظات (اختياري)',
    add_btn_label_add: 'أضف الغاتورة',
    add_btn_label_save: 'حفظ التغييرات',
    add_error_msg: 'الرجاء إدخال إسم و قيمة الفاتورة',
    edit_heading: 'تعديل الفاتورة',
    edit_btn_remove: 'حذف',
    edit_btn_cancel: 'إلغاء'
  }
}